### CSE-221710304057-T.Snithika Patel

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/sumathi16/Datasets/master/Human_Resources_Employee_Attrition.csv")
df=data.head(200)
df

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales,low
171,0.41,0.46,2,160,3,0,1,1,sales,low
172,0.11,0.78,7,278,4,0,1,0,sales,low
173,0.10,0.88,6,284,4,0,1,0,sales,low
174,0.70,0.53,2,274,4,0,1,0,sales,low
175,0.54,0.74,4,164,2,0,1,0,sales,low
176,0.41,0.48,2,148,3,0,1,0,sales,low
177,0.38,0.50,2,140,3,0,1,0,sales,medium
178,0.37,0.51,2,127,3,0,1,0,sales,medium
179,0.11,0.85,6,308,5,0,1,0,sales,medium
180,0.40,0.47,2,146,3,0,1,0,sales,medium
181,0.10,0.84,6,261,4,0,1,0,accounting,medium
182,0.89,0.99,5,257,5,0,1,0,accounting,medium
183,0.11,0.80,6,285,4,0,1,0,accounting,medium
184,0.36,0.55,2,141,3,0,1,0,hr,medium
185,0.40,0.46,2,127,3,0,1,0,hr,medium
186,0.09,0.85,6,297,4,0,1,0,hr,medium
187,0.40,0.46,2,143,3,0,1,0,hr,medium
188,0.37,0.55,2,152,3,0,1,0,technical,medium
189,0.44,0.51,2,156,3,0,1,0,technical,high
190,0.09,0.80,7,283,5,0,1,0,technical,low
191,0.92,0.87,4,226,6,1,1,0,technical,medium
192,0.74,0.91,4,232,5,0,1,0,technical,medium
193,0.09,0.82,6,249,4,0,1,0,technical,medium
194,0.89,0.95,4,275,5,0,1,0,technical,medium
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

What is the data separator?

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/sumathi16/Datasets/master/Human_Resources_Employee_Attrition.csv",sep=",")
df=data.head(200)   #separator used is comma(,)
df

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales,low
171,0.41,0.46,2,160,3,0,1,1,sales,low
172,0.11,0.78,7,278,4,0,1,0,sales,low
173,0.10,0.88,6,284,4,0,1,0,sales,low
174,0.70,0.53,2,274,4,0,1,0,sales,low
175,0.54,0.74,4,164,2,0,1,0,sales,low
176,0.41,0.48,2,148,3,0,1,0,sales,low
177,0.38,0.50,2,140,3,0,1,0,sales,medium
178,0.37,0.51,2,127,3,0,1,0,sales,medium
179,0.11,0.85,6,308,5,0,1,0,sales,medium
180,0.40,0.47,2,146,3,0,1,0,sales,medium
181,0.10,0.84,6,261,4,0,1,0,accounting,medium
182,0.89,0.99,5,257,5,0,1,0,accounting,medium
183,0.11,0.80,6,285,4,0,1,0,accounting,medium
184,0.36,0.55,2,141,3,0,1,0,hr,medium
185,0.40,0.46,2,127,3,0,1,0,hr,medium
186,0.09,0.85,6,297,4,0,1,0,hr,medium
187,0.40,0.46,2,143,3,0,1,0,hr,medium
188,0.37,0.55,2,152,3,0,1,0,technical,medium
189,0.44,0.51,2,156,3,0,1,0,technical,high
190,0.09,0.80,7,283,5,0,1,0,technical,low
191,0.92,0.87,4,226,6,1,1,0,technical,medium
192,0.74,0.91,4,232,5,0,1,0,technical,medium
193,0.09,0.82,6,249,4,0,1,0,technical,medium
194,0.89,0.95,4,275,5,0,1,0,technical,medium
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

Is the data contains header?

In [4]:
list(df)

['satisfaction_level',
 'last_evaluation',
 'number_of_projects',
 'average_monthly_hours',
 'years_at_company',
 'work_accident',
 'left',
 'promotion_last_5years',
 'department',
 'salary']

After getting the data as a dataframe check how many rows and columns are there?

In [5]:
df.shape

(200, 10)

### Check how many categorical and numerical columns are there?
     Categorical - object type
     Numerical - int,float
     Boolean - bool

In [6]:
len(df.select_dtypes(include=['int64','float64']).columns)

8

In [7]:
len(df.select_dtypes(exclude=['int64','float64']).columns)

2

In [8]:
categorical=0
numerical=0
boolean=0
for j in df.dtypes:
    if j=="object":
        categorical += 1
    elif j=="bool":
        boolean += 1
    else:
        numerical += 1
print("No :of object type and int type columns and boolean type columns are",categorical,"and",numerical,"and",boolean,"respectively")

No :of object type and int type columns and boolean type columns are 2 and 8 and 0 respectively

Create a copy of the dataframe. Later on perform the operations on a new dataframe.

In [9]:
df_new = df.copy()
df_new

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales,low
171,0.41,0.46,2,160,3,0,1,1,sales,low
172,0.11,0.78,7,278,4,0,1,0,sales,low
173,0.10,0.88,6,284,4,0,1,0,sales,low
174,0.70,0.53,2,274,4,0,1,0,sales,low
175,0.54,0.74,4,164,2,0,1,0,sales,low
176,0.41,0.48,2,148,3,0,1,0,sales,low
177,0.38,0.50,2,140,3,0,1,0,sales,medium
178,0.37,0.51,2,127,3,0,1,0,sales,medium
179,0.11,0.85,6,308,5,0,1,0,sales,medium
180,0.40,0.47,2,146,3,0,1,0,sales,medium
181,0.10,0.84,6,261,4,0,1,0,accounting,medium
182,0.89,0.99,5,257,5,0,1,0,accounting,medium
183,0.11,0.80,6,285,4,0,1,0,accounting,medium
184,0.36,0.55,2,141,3,0,1,0,hr,medium
185,0.40,0.46,2,127,3,0,1,0,hr,medium
186,0.09,0.85,6,297,4,0,1,0,hr,medium
187,0.40,0.46,2,143,3,0,1,0,hr,medium
188,0.37,0.55,2,152,3,0,1,0,technical,medium
189,0.44,0.51,2,156,3,0,1,0,technical,high
190,0.09,0.80,7,283,5,0,1,0,technical,low
191,0.92,0.87,4,226,6,1,1,0,technical,medium
192,0.74,0.91,4,232,5,0,1,0,technical,medium
193,0.09,0.82,6,249,4,0,1,0,technical,medium
194,0.89,0.95,4,275,5,0,1,0,technical,medium
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

### Observe the data and check for missing data and duplicates based on entire data.
    Remove the duplicates 
    Replace the missing values with a function of your choice

In [10]:
df_new.isna().sum()

satisfaction_level       0
last_evaluation          0
number_of_projects       0
average_monthly_hours    0
years_at_company         0
work_accident            0
left                     0
promotion_last_5years    0
department               0
salary                   0
dtype: int64

In [11]:
df_new.drop_duplicates()

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales,low
171,0.41,0.46,2,160,3,0,1,1,sales,low
172,0.11,0.78,7,278,4,0,1,0,sales,low
173,0.10,0.88,6,284,4,0,1,0,sales,low
174,0.70,0.53,2,274,4,0,1,0,sales,low
175,0.54,0.74,4,164,2,0,1,0,sales,low
176,0.41,0.48,2,148,3,0,1,0,sales,low
177,0.38,0.50,2,140,3,0,1,0,sales,medium
178,0.37,0.51,2,127,3,0,1,0,sales,medium
179,0.11,0.85,6,308,5,0,1,0,sales,medium
180,0.40,0.47,2,146,3,0,1,0,sales,medium
181,0.10,0.84,6,261,4,0,1,0,accounting,medium
182,0.89,0.99,5,257,5,0,1,0,accounting,medium
183,0.11,0.80,6,285,4,0,1,0,accounting,medium
184,0.36,0.55,2,141,3,0,1,0,hr,medium
185,0.40,0.46,2,127,3,0,1,0,hr,medium
186,0.09,0.85,6,297,4,0,1,0,hr,medium
187,0.40,0.46,2,143,3,0,1,0,hr,medium
188,0.37,0.55,2,152,3,0,1,0,technical,medium
189,0.44,0.51,2,156,3,0,1,0,technical,high
190,0.09,0.80,7,283,5,0,1,0,technical,low
191,0.92,0.87,4,226,6,1,1,0,technical,medium
192,0.74,0.91,4,232,5,0,1,0,technical,medium
193,0.09,0.82,6,249,4,0,1,0,technical,medium
194,0.89,0.95,4,275,5,0,1,0,technical,medium
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

Apply labelEncoder to a categorical column

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [14]:
employee_data = df_new.copy()
employee_data

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales,low
171,0.41,0.46,2,160,3,0,1,1,sales,low
172,0.11,0.78,7,278,4,0,1,0,sales,low
173,0.10,0.88,6,284,4,0,1,0,sales,low
174,0.70,0.53,2,274,4,0,1,0,sales,low
175,0.54,0.74,4,164,2,0,1,0,sales,low
176,0.41,0.48,2,148,3,0,1,0,sales,low
177,0.38,0.50,2,140,3,0,1,0,sales,medium
178,0.37,0.51,2,127,3,0,1,0,sales,medium
179,0.11,0.85,6,308,5,0,1,0,sales,medium
180,0.40,0.47,2,146,3,0,1,0,sales,medium
181,0.10,0.84,6,261,4,0,1,0,accounting,medium
182,0.89,0.99,5,257,5,0,1,0,accounting,medium
183,0.11,0.80,6,285,4,0,1,0,accounting,medium
184,0.36,0.55,2,141,3,0,1,0,hr,medium
185,0.40,0.46,2,127,3,0,1,0,hr,medium
186,0.09,0.85,6,297,4,0,1,0,hr,medium
187,0.40,0.46,2,143,3,0,1,0,hr,medium
188,0.37,0.55,2,152,3,0,1,0,technical,medium
189,0.44,0.51,2,156,3,0,1,0,technical,high
190,0.09,0.80,7,283,5,0,1,0,technical,low
191,0.92,0.87,4,226,6,1,1,0,technical,medium
192,0.74,0.91,4,232,5,0,1,0,technical,medium
193,0.09,0.82,6,249,4,0,1,0,technical,medium
194,0.89,0.95,4,275,5,0,1,0,technical,medium
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

In [15]:
employee_data.department = le.fit_transform(df_new.department)
employee_data

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,6,low
1,0.80,0.86,5,262,6,0,1,0,6,medium
2,0.11,0.88,7,272,4,0,1,0,6,medium
3,0.72,0.87,5,223,5,0,1,0,6,low
4,0.37,0.52,2,159,3,0,1,0,6,low
5,0.41,0.50,2,153,3,0,1,0,6,low
6,0.10,0.77,6,247,4,0,1,0,6,low
7,0.92,0.85,5,259,5,0,1,0,6,low
8,0.89,1.00,5,224,5,0,1,0,6,low
9,0.42,0.53,2,142,3,0,1,0,6,low
10,0.45,0.54,2,135,3,0,1,0,6,low
11,0.11,0.81,6,305,4,0,1,0,6,low
12,0.84,0.92,4,234,5,0,1,0,6,low
13,0.41,0.55,2,148,3,0,1,0,6,low
14,0.36,0.56,2,137,3,0,1,0,6,low
15,0.38,0.54,2,143,3,0,1,0,6,low
16,0.45,0.47,2,160,3,0,1,0,6,low
17,0.78,0.99,4,255,6,0,1,0,6,low
18,0.45,0.51,2,160,3,1,1,1,6,low
19,0.76,0.89,5,262,5,0,1,0,6,low
20,0.11,0.83,6,282,4,0,1,0,6,low
21,0.38,0.55,2,147,3,0,1,0,6,low
22,0.09,0.95,6,304,4,0,1,0,6,low
23,0.46,0.57,2,139,3,0,1,0,6,low
24,0.40,0.53,2,158,3,0,1,0,6,low
25,0.89,0.92,5,242,5,0,1,0,6,low
26,0.82,0.87,4,239,5,0,1,0,6,low
27,0.40,0.49,2,135,3,0,1,0,6,low
28,0.41,0.46,2,128,3,0,1,0,1,low
29,0.38,0.50,2,132,3,0,1,0,1,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,6,low
171,0.41,0.46,2,160,3,0,1,1,6,low
172,0.11,0.78,7,278,4,0,1,0,6,low
173,0.10,0.88,6,284,4,0,1,0,6,low
174,0.70,0.53,2,274,4,0,1,0,6,low
175,0.54,0.74,4,164,2,0,1,0,6,low
176,0.41,0.48,2,148,3,0,1,0,6,low
177,0.38,0.50,2,140,3,0,1,0,6,medium
178,0.37,0.51,2,127,3,0,1,0,6,medium
179,0.11,0.85,6,308,5,0,1,0,6,medium
180,0.40,0.47,2,146,3,0,1,0,6,medium
181,0.10,0.84,6,261,4,0,1,0,1,medium
182,0.89,0.99,5,257,5,0,1,0,1,medium
183,0.11,0.80,6,285,4,0,1,0,1,medium
184,0.36,0.55,2,141,3,0,1,0,2,medium
185,0.40,0.46,2,127,3,0,1,0,2,medium
186,0.09,0.85,6,297,4,0,1,0,2,medium
187,0.40,0.46,2,143,3,0,1,0,2,medium
188,0.37,0.55,2,152,3,0,1,0,8,medium
189,0.44,0.51,2,156,3,0,1,0,8,high
190,0.09,0.80,7,283,5,0,1,0,8,low
191,0.92,0.87,4,226,6,1,1,0,8,medium
192,0.74,0.91,4,232,5,0,1,0,8,medium
193,0.09,0.82,6,249,4,0,1,0,8,medium
194,0.89,0.95,4,275,5,0,1,0,8,medium
195,0.09,0.80,6,304,4,0,1,0,8,low
196,0.27,0.54,7,278,3,0,1,0,8,low
197,0.10,0.91,6,287,4,0,1,0,8,low
198,0.10,0.89,7,285,4,0,1,0,8,low
199,0.77,0.94,5,226,6,0,1,0,7,low

In [16]:
employee_data.salary = le.fit_transform(df_new.salary)
employee_data

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,6,1
1,0.80,0.86,5,262,6,0,1,0,6,2
2,0.11,0.88,7,272,4,0,1,0,6,2
3,0.72,0.87,5,223,5,0,1,0,6,1
4,0.37,0.52,2,159,3,0,1,0,6,1
5,0.41,0.50,2,153,3,0,1,0,6,1
6,0.10,0.77,6,247,4,0,1,0,6,1
7,0.92,0.85,5,259,5,0,1,0,6,1
8,0.89,1.00,5,224,5,0,1,0,6,1
9,0.42,0.53,2,142,3,0,1,0,6,1
10,0.45,0.54,2,135,3,0,1,0,6,1
11,0.11,0.81,6,305,4,0,1,0,6,1
12,0.84,0.92,4,234,5,0,1,0,6,1
13,0.41,0.55,2,148,3,0,1,0,6,1
14,0.36,0.56,2,137,3,0,1,0,6,1
15,0.38,0.54,2,143,3,0,1,0,6,1
16,0.45,0.47,2,160,3,0,1,0,6,1
17,0.78,0.99,4,255,6,0,1,0,6,1
18,0.45,0.51,2,160,3,1,1,1,6,1
19,0.76,0.89,5,262,5,0,1,0,6,1
20,0.11,0.83,6,282,4,0,1,0,6,1
21,0.38,0.55,2,147,3,0,1,0,6,1
22,0.09,0.95,6,304,4,0,1,0,6,1
23,0.46,0.57,2,139,3,0,1,0,6,1
24,0.40,0.53,2,158,3,0,1,0,6,1
25,0.89,0.92,5,242,5,0,1,0,6,1
26,0.82,0.87,4,239,5,0,1,0,6,1
27,0.40,0.49,2,135,3,0,1,0,6,1
28,0.41,0.46,2,128,3,0,1,0,1,1
29,0.38,0.50,2,132,3,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,6,1
171,0.41,0.46,2,160,3,0,1,1,6,1
172,0.11,0.78,7,278,4,0,1,0,6,1
173,0.10,0.88,6,284,4,0,1,0,6,1
174,0.70,0.53,2,274,4,0,1,0,6,1
175,0.54,0.74,4,164,2,0,1,0,6,1
176,0.41,0.48,2,148,3,0,1,0,6,1
177,0.38,0.50,2,140,3,0,1,0,6,2
178,0.37,0.51,2,127,3,0,1,0,6,2
179,0.11,0.85,6,308,5,0,1,0,6,2
180,0.40,0.47,2,146,3,0,1,0,6,2
181,0.10,0.84,6,261,4,0,1,0,1,2
182,0.89,0.99,5,257,5,0,1,0,1,2
183,0.11,0.80,6,285,4,0,1,0,1,2
184,0.36,0.55,2,141,3,0,1,0,2,2
185,0.40,0.46,2,127,3,0,1,0,2,2
186,0.09,0.85,6,297,4,0,1,0,2,2
187,0.40,0.46,2,143,3,0,1,0,2,2
188,0.37,0.55,2,152,3,0,1,0,8,2
189,0.44,0.51,2,156,3,0,1,0,8,0
190,0.09,0.80,7,283,5,0,1,0,8,1
191,0.92,0.87,4,226,6,1,1,0,8,2
192,0.74,0.91,4,232,5,0,1,0,8,2
193,0.09,0.82,6,249,4,0,1,0,8,2
194,0.89,0.95,4,275,5,0,1,0,8,2
195,0.09,0.80,6,304,4,0,1,0,8,1
196,0.27,0.54,7,278,3,0,1,0,8,1
197,0.10,0.91,6,287,4,0,1,0,8,1
198,0.10,0.89,7,285,4,0,1,0,8,1
199,0.77,0.94,5,226,6,0,1,0,7,1

Apply onehotencoder to a categorical column

In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('Encoder',OneHotEncoder(),['department'])],remainder="passthrough")

df_new=ct.fit_transform(df)
df_new=pd.DataFrame(df_new)
df_new=df_new.iloc[:,0:9]
df_new.columns=['dep_sales','dep_technical','dep_support','dep_product_mng','dep_marketing','dep_IT','dep_hr',
              'dep_accounting','dep_management']
df_new=pd.concat([df,df_new],axis=1)
df_new=df_new.drop('department',axis=1)
df_new

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,salary,dep_sales,dep_technical,dep_support,dep_product_mng,dep_marketing,dep_IT,dep_hr,dep_accounting,dep_management
0,0.38,0.53,2,157,3,0,1,0,low,0,0,0,0,0,0,1,0,0
1,0.80,0.86,5,262,6,0,1,0,medium,0,0,0,0,0,0,1,0,0
2,0.11,0.88,7,272,4,0,1,0,medium,0,0,0,0,0,0,1,0,0
3,0.72,0.87,5,223,5,0,1,0,low,0,0,0,0,0,0,1,0,0
4,0.37,0.52,2,159,3,0,1,0,low,0,0,0,0,0,0,1,0,0
5,0.41,0.50,2,153,3,0,1,0,low,0,0,0,0,0,0,1,0,0
6,0.10,0.77,6,247,4,0,1,0,low,0,0,0,0,0,0,1,0,0
7,0.92,0.85,5,259,5,0,1,0,low,0,0,0,0,0,0,1,0,0
8,0.89,1.00,5,224,5,0,1,0,low,0,0,0,0,0,0,1,0,0
9,0.42,0.53,2,142,3,0,1,0,low,0,0,0,0,0,0,1,0,0
10,0.45,0.54,2,135,3,0,1,0,low,0,0,0,0,0,0,1,0,0
11,0.11,0.81,6,305,4,0,1,0,low,0,0,0,0,0,0,1,0,0
12,0.84,0.92,4,234,5,0,1,0,low,0,0,0,0,0,0,1,0,0
13,0.41,0.55,2,148,3,0,1,0,low,0,0,0,0,0,0,1,0,0
14,0.36,0.56,2,137,3,0,1,0,low,0,0,0,0,0,0,1,0,0
15,0.38,0.54,2,143,3,0,1,0,low,0,0,0,0,0,0,1,0,0
16,0.45,0.47,2,160,3,0,1,0,low,0,0,0,0,0,0,1,0,0
17,0.78,0.99,4,255,6,0,1,0,low,0,0,0,0,0,0,1,0,0
18,0.45,0.51,2,160,3,1,1,1,low,0,0,0,0,0,0,1,0,0
19,0.76,0.89,5,262,5,0,1,0,low,0,0,0,0,0,0,1,0,0
20,0.11,0.83,6,282,4,0,1,0,low,0,0,0,0,0,0,1,0,0
21,0.38,0.55,2,147,3,0,1,0,low,0,0,0,0,0,0,1,0,0
22,0.09,0.95,6,304,4,0,1,0,low,0,0,0,0,0,0,1,0,0
23,0.46,0.57,2,139,3,0,1,0,low,0,0,0,0,0,0,1,0,0
24,0.40,0.53,2,158,3,0,1,0,low,0,0,0,0,0,0,1,0,0
25,0.89,0.92,5,242,5,0,1,0,low,0,0,0,0,0,0,1,0,0
26,0.82,0.87,4,239,5,0,1,0,low,0,0,0,0,0,0,1,0,0
27,0.40,0.49,2,135,3,0,1,0,low,0,0,0,0,0,0,1,0,0
28,0.41,0.46,2,128,3,0,1,0,low,0,1,0,0,0,0,0,0,0
29,0.38,0.50,2,132,3,0,1,0,low,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,low,0,0,0,0,0,0,1,0,0
171,0.41,0.46,2,160,3,0,1,1,low,0,0,0,0,0,0,1,0,0
172,0.11,0.78,7,278,4,0,1,0,low,0,0,0,0,0,0,1,0,0
173,0.10,0.88,6,284,4,0,1,0,low,0,0,0,0,0,0,1,0,0
174,0.70,0.53,2,274,4,0,1,0,low,0,0,0,0,0,0,1,0,0
175,0.54,0.74,4,164,2,0,1,0,low,0,0,0,0,0,0,1,0,0
176,0.41,0.48,2,148,3,0,1,0,low,0,0,0,0,0,0,1,0,0
177,0.38,0.50,2,140,3,0,1,0,medium,0,0,0,0,0,0,1,0,0
178,0.37,0.51,2,127,3,0,1,0,medium,0,0,0,0,0,0,1,0,0
179,0.11,0.85,6,308,5,0,1,0,medium,0,0,0,0,0,0,1,0,0
180,0.40,0.47,2,146,3,0,1,0,medium,0,0,0,0,0,0,1,0,0
181,0.10,0.84,6,261,4,0,1,0,medium,0,1,0,0,0,0,0,0,0
182,0.89,0.99,5,257,5,0,1,0,medium,0,1,0,0,0,0,0,0,0
183,0.11,0.80,6,285,4,0,1,0,medium,0,1,0,0,0,0,0,0,0
184,0.36,0.55,2,141,3,0,1,0,medium,0,0,1,0,0,0,0,0,0
185,0.40,0.46,2,127,3,0,1,0,medium,0,0,1,0,0,0,0,0,0
186,0.09,0.85,6,297,4,0,1,0,medium,0,0,1,0,0,0,0,0,0
187,0.40,0.46,2,143,3,0,1,0,medium,0,0,1,0,0,0,0,0,0
188,0.37,0.55,2,152,3,0,1,0,medium,0,0,0,0,0,0,0,0,1
189,0.44,0.51,2,156,3,0,1,0,high,0,0,0,0,0,0,0,0,1
190,0.09,0.80,7,283,5,0,1,0,low,0,0,0,0,0,0,0,0,1
191,0.92,0.87,4,226,6,1,1,0,medium,0,0,0,0,0,0,0,0,1
192,0.74,0.91,4,232,5,0,1,0,medium,0,0,0,0,0,0,0,0,1
193,0.09,0.82,6,249,4,0,1,0,medium,0,0,0,0,0,0,0,0,1
194,0.89,0.95,4,275,5,0,1,0,medium,0,0,0,0,0,0,0,0,1
195,0.09,0.80,6,304,4,0,1,0,low,0,0,0,0,0,0,0,0,1
196,0.27,0.54,7,278,3,0,1,0,low,0,0,0,0,0,0,0,0,1
197,0.10,0.91,6,287,4,0,1,0,low,0,0,0,0,0,0,0,0,1
198,0.10,0.89,7,285,4,0,1,0,low,0,0,0,0,0,0,0,0,1
199,0.77,0.94,5,226,6,0,1,0,low,0,0,0,0,0,0,0,1,0

Apply standard scaler for all the columns

In [18]:
sample = employee_data.copy()
sample

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,6,1
1,0.80,0.86,5,262,6,0,1,0,6,2
2,0.11,0.88,7,272,4,0,1,0,6,2
3,0.72,0.87,5,223,5,0,1,0,6,1
4,0.37,0.52,2,159,3,0,1,0,6,1
5,0.41,0.50,2,153,3,0,1,0,6,1
6,0.10,0.77,6,247,4,0,1,0,6,1
7,0.92,0.85,5,259,5,0,1,0,6,1
8,0.89,1.00,5,224,5,0,1,0,6,1
9,0.42,0.53,2,142,3,0,1,0,6,1
10,0.45,0.54,2,135,3,0,1,0,6,1
11,0.11,0.81,6,305,4,0,1,0,6,1
12,0.84,0.92,4,234,5,0,1,0,6,1
13,0.41,0.55,2,148,3,0,1,0,6,1
14,0.36,0.56,2,137,3,0,1,0,6,1
15,0.38,0.54,2,143,3,0,1,0,6,1
16,0.45,0.47,2,160,3,0,1,0,6,1
17,0.78,0.99,4,255,6,0,1,0,6,1
18,0.45,0.51,2,160,3,1,1,1,6,1
19,0.76,0.89,5,262,5,0,1,0,6,1
20,0.11,0.83,6,282,4,0,1,0,6,1
21,0.38,0.55,2,147,3,0,1,0,6,1
22,0.09,0.95,6,304,4,0,1,0,6,1
23,0.46,0.57,2,139,3,0,1,0,6,1
24,0.40,0.53,2,158,3,0,1,0,6,1
25,0.89,0.92,5,242,5,0,1,0,6,1
26,0.82,0.87,4,239,5,0,1,0,6,1
27,0.40,0.49,2,135,3,0,1,0,6,1
28,0.41,0.46,2,128,3,0,1,0,1,1
29,0.38,0.50,2,132,3,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,6,1
171,0.41,0.46,2,160,3,0,1,1,6,1
172,0.11,0.78,7,278,4,0,1,0,6,1
173,0.10,0.88,6,284,4,0,1,0,6,1
174,0.70,0.53,2,274,4,0,1,0,6,1
175,0.54,0.74,4,164,2,0,1,0,6,1
176,0.41,0.48,2,148,3,0,1,0,6,1
177,0.38,0.50,2,140,3,0,1,0,6,2
178,0.37,0.51,2,127,3,0,1,0,6,2
179,0.11,0.85,6,308,5,0,1,0,6,2
180,0.40,0.47,2,146,3,0,1,0,6,2
181,0.10,0.84,6,261,4,0,1,0,1,2
182,0.89,0.99,5,257,5,0,1,0,1,2
183,0.11,0.80,6,285,4,0,1,0,1,2
184,0.36,0.55,2,141,3,0,1,0,2,2
185,0.40,0.46,2,127,3,0,1,0,2,2
186,0.09,0.85,6,297,4,0,1,0,2,2
187,0.40,0.46,2,143,3,0,1,0,2,2
188,0.37,0.55,2,152,3,0,1,0,8,2
189,0.44,0.51,2,156,3,0,1,0,8,0
190,0.09,0.80,7,283,5,0,1,0,8,1
191,0.92,0.87,4,226,6,1,1,0,8,2
192,0.74,0.91,4,232,5,0,1,0,8,2
193,0.09,0.82,6,249,4,0,1,0,8,2
194,0.89,0.95,4,275,5,0,1,0,8,2
195,0.09,0.80,6,304,4,0,1,0,8,1
196,0.27,0.54,7,278,3,0,1,0,8,1
197,0.10,0.91,6,287,4,0,1,0,8,1
198,0.10,0.89,7,285,4,0,1,0,8,1
199,0.77,0.94,5,226,6,0,1,0,7,1

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #creating object
sample = sc.fit_transform(sample)
sample

array([[-0.1291856 , -0.89505158, -0.98361129, ..., -0.12340351,
         0.25377296, -0.51308698],
       [ 1.47370815,  0.80343618,  0.61143404, ..., -0.12340351,
         0.25377296,  1.67026188],
       [-1.1596173 ,  0.90637483,  1.6747976 , ..., -0.12340351,
         0.25377296,  1.67026188],
       ...,
       [-1.19778144,  1.06078281,  1.14311582, ..., -0.12340351,
         1.09968283, -0.51308698],
       [-1.19778144,  0.95784416,  1.6747976 , ..., -0.12340351,
         1.09968283, -0.51308698],
       [ 1.35921574,  1.21519079,  0.61143404, ..., -0.12340351,
         0.6767279 , -0.51308698]])

In [20]:
sample = pd.DataFrame(sample)
sample

,0,1,2,3,4,5,6,7,8,9
0,-0.129186,-0.895052,-0.983611,-0.756906,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
1,1.473708,0.803436,0.611434,0.877208,2.331995,-0.190445,0.0,-0.123404,0.253773,1.670262
2,-1.159617,0.906375,1.674798,1.032838,0.212000,-0.190445,0.0,-0.123404,0.253773,1.670262
3,1.168395,0.854906,0.611434,0.270251,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
4,-0.167350,-0.946521,-0.983611,-0.725780,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
5,-0.014693,-1.049460,-0.983611,-0.819158,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
6,-1.197781,0.340212,1.143116,0.643763,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
7,1.931678,0.751967,0.611434,0.830519,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
8,1.817185,1.524007,0.611434,0.285814,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
9,0.023471,-0.895052,-0.983611,-0.990351,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
10,0.137963,-0.843582,-0.983611,-1.099292,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
11,-1.159617,0.546090,1.143116,1.546417,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
12,1.626365,1.112252,0.079752,0.441444,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
13,-0.014693,-0.792113,-0.983611,-0.896973,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
14,-0.205514,-0.740644,-0.983611,-1.068166,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
15,-0.129186,-0.843582,-0.983611,-0.974788,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
16,0.137963,-1.203868,-0.983611,-0.710217,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
17,1.397380,1.472537,0.079752,0.768267,2.331995,-0.190445,0.0,-0.123404,0.253773,-0.513087
18,0.137963,-0.997990,-0.983611,-0.710217,-0.847998,5.250850,0.0,8.103497,0.253773,-0.513087
19,1.321052,0.957844,0.611434,0.877208,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
20,-1.159617,0.649028,1.143116,1.188468,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
21,-0.129186,-0.792113,-0.983611,-0.912536,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
22,-1.235946,1.266660,1.143116,1.530854,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
23,0.176127,-0.689174,-0.983611,-1.037040,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
24,-0.052857,-0.895052,-0.983611,-0.741343,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
25,1.817185,1.112252,0.611434,0.565948,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
26,1.550036,0.854906,0.079752,0.519259,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
27,-0.052857,-1.100929,-0.983611,-1.099292,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
28,-0.014693,-1.255337,-0.983611,-1.208233,-0.847998,-0.190445,0.0,-0.123404,-1.861002,-0.513087
29,-0.129186,-1.049460,-0.983611,-1.145981,-0.847998,-0.190445,0.0,-0.123404,-1.861002,-0.513087
...,...,...,...,...,...,...,...,...,...,...
170,1.511872,1.472537,0.079752,0.830519,1.271997,-0.190445,0.0,-0.123404,0.253773,-0.513087
171,-0.014693,-1.255337,-0.983611,-0.710217,-0.847998,-0.190445,0.0,8.103497,0.253773,-0.513087
172,-1.159617,0.391682,1.674798,1.126216,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
173,-1.197781,0.906375,1.143116,1.219594,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
174,1.092067,-0.895052,-0.983611,1.063964,0.212000,-0.190445,0.0,-0.123404,0.253773,-0.513087
175,0.481441,0.185804,0.079752,-0.647965,-1.907996,-0.190445,0.0,-0.123404,0.253773,-0.513087
176,-0.014693,-1.152398,-0.983611,-0.896973,-0.847998,-0.190445,0.0,-0.123404,0.253773,-0.513087
177,-0.129186,-1.049460,-0.983611,-1.021477,-0.847998,-0.190445,0.0,-0.123404,0.253773,1.670262
178,-0.167350,-0.997990,-0.983611,-1.223796,-0.847998,-0.190445,0.0,-0.123404,0.253773,1.670262
179,-1.159617,0.751967,1.143116,1.593106,1.271997,-0.190445,0.0,-0.123404,0.253773,1.670262
180,-0.052857,-1.203868,-0.983611,-0.928099,-0.847998,-0.190445,0.0,-0.123404,0.253773,1.670262
181,-1.197781,0.700498,1.143116,0.861645,0.212000,-0.190445,0.0,-0.123404,-1.861002,1.670262
182,1.817185,1.472537,0.611434,0.799393,1.271997,-0.190445,0.0,-0.123404,-1.861002,1.670262
183,-1.159617,0.494620,1.143116,1.235157,0.212000,-0.190445,0.0,-0.123404,-1.861002,1.670262
184,-0.205514,-0.792113,-0.983611,-1.005914,-0.847998,-0.190445,0.0,-0.123404,-1.438047,1.670262
185,-0.052857,-1.255337,-0.983611,-1.223796,-0.847998,-0.190445,0.0,-0.123404,-1.438047,1.670262
186,-1.235946,0.751967,1.143116,1.421913,0.212000,-0.190445,0.0,-0.123404,-1.438047,1.670262
187,-0.052857,-1.255337,-0.983611,-0.974788,-0.847998,-0.190445,0.0,-0.123404,-1.438047,1.670262
188,-0.167350,-0.792113,-0.983611,-0.834721,-0.847998,-0.190445,0.0,-0.123404,1.099683,1.670262
189,0.099799,-0.997990,-0.983611,-0.772469,-0.847998,-0.190445,0.0,-0.123404,1.099683,-2.696436
190,-1.235946,0.494620,1.674798,1.204031,1.271997,-0.190445,0.0,-0.123404,1.099683,-0.513087
191,1.931678,0.854906,0.079752,0.316940,2.331995,5.250850,0.0,-0.123404,1.099683,1.670262
192,1.244723,1.060783,0.079752,0.410318,1.271997,-0.190445,0.0,-0.123404,1.099683,1.670262
193,-1.235946,0.597559,1.143116,0.674889,0.212000,-0.190445,0.0,-0.123404,1.099683,1.670262
194,1.817185,1.266660,0.079752,1.079527,1.271997,-0.190445,0.0,-0.123404,1.099683,1.670262
195,-1.235946,0.494620,1.143116,1.530854,0.212000,-0.190445,0.0,-0.123404,1.099683,-0.513087
196,-0.548991,-0.843582,1.674798,1.126216,-0.847998,-0.190445,0.0,-0.123404,1.099683,-0.513087
197,-1.197781,1.060783,1.143116,1.266283,0.212000,-0.190445,0.0,-0.123404,1.099683,-0.513087
198,-1.197781,0.957844,1.674798,1.235157,0.212000,-0.190445,0.0,-0.123404,1.099683,-0.513087
199,1.359216,1.215191,0.611434,0.316940,2.331995,-0.190445,0.0,-0.123404,0.676728,-0.513087

Apply pd.get_dummies for the entire data frame and check how many columns added.

In [22]:
newd1=df.copy()
newd1=pd.get_dummies(newd1,columns=['department','salary'])
newd1

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department_IT,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1,0.80,0.86,5,262,6,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
2,0.11,0.88,7,272,4,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
3,0.72,0.87,5,223,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.37,0.52,2,159,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
5,0.41,0.50,2,153,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
6,0.10,0.77,6,247,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
7,0.92,0.85,5,259,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
8,0.89,1.00,5,224,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
9,0.42,0.53,2,142,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
10,0.45,0.54,2,135,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
11,0.11,0.81,6,305,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
12,0.84,0.92,4,234,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
13,0.41,0.55,2,148,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
14,0.36,0.56,2,137,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
15,0.38,0.54,2,143,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
16,0.45,0.47,2,160,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
17,0.78,0.99,4,255,6,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
18,0.45,0.51,2,160,3,1,1,1,0,0,0,0,0,0,1,0,0,0,1,0
19,0.76,0.89,5,262,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
20,0.11,0.83,6,282,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
21,0.38,0.55,2,147,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
22,0.09,0.95,6,304,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
23,0.46,0.57,2,139,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
24,0.40,0.53,2,158,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
25,0.89,0.92,5,242,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
26,0.82,0.87,4,239,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
27,0.40,0.49,2,135,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
28,0.41,0.46,2,128,3,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0
29,0.38,0.50,2,132,3,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
171,0.41,0.46,2,160,3,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0
172,0.11,0.78,7,278,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
173,0.10,0.88,6,284,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
174,0.70,0.53,2,274,4,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
175,0.54,0.74,4,164,2,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
176,0.41,0.48,2,148,3,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
177,0.38,0.50,2,140,3,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
178,0.37,0.51,2,127,3,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
179,0.11,0.85,6,308,5,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
180,0.40,0.47,2,146,3,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
181,0.10,0.84,6,261,4,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1
182,0.89,0.99,5,257,5,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1
183,0.11,0.80,6,285,4,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1
184,0.36,0.55,2,141,3,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
185,0.40,0.46,2,127,3,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
186,0.09,0.85,6,297,4,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
187,0.40,0.46,2,143,3,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1
188,0.37,0.55,2,152,3,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1
189,0.44,0.51,2,156,3,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0
190,0.09,0.80,7,283,5,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0
191,0.92,0.87,4,226,6,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1
192,0.74,0.91,4,232,5,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1
193,0.09,0.82,6,249,4,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1
194,0.89,0.95,4,275,5,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1
195,0.09,0.80,6,304,4,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0
196,0.27,0.54,7,278,3,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0
197,0.10,0.91,6,287,4,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0
198,0.10,0.89,7,285,4,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0
199,0.77,0.94,5,226,6,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0

In [23]:
print("no of column added  are:",len(newd1.columns)-len(df.columns)+len(df.select_dtypes(include=['object']).columns))

no of column added  are: 12

In [24]:
df = pd.read_csv("https://raw.githubusercontent.com/sumathi16/Datasets/master/Human_Resources_Employee_Attrition.csv").head(200)
df

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low
5,0.41,0.50,2,153,3,0,1,0,sales,low
6,0.10,0.77,6,247,4,0,1,0,sales,low
7,0.92,0.85,5,259,5,0,1,0,sales,low
8,0.89,1.00,5,224,5,0,1,0,sales,low
9,0.42,0.53,2,142,3,0,1,0,sales,low
10,0.45,0.54,2,135,3,0,1,0,sales,low
11,0.11,0.81,6,305,4,0,1,0,sales,low
12,0.84,0.92,4,234,5,0,1,0,sales,low
13,0.41,0.55,2,148,3,0,1,0,sales,low
14,0.36,0.56,2,137,3,0,1,0,sales,low
15,0.38,0.54,2,143,3,0,1,0,sales,low
16,0.45,0.47,2,160,3,0,1,0,sales,low
17,0.78,0.99,4,255,6,0,1,0,sales,low
18,0.45,0.51,2,160,3,1,1,1,sales,low
19,0.76,0.89,5,262,5,0,1,0,sales,low
20,0.11,0.83,6,282,4,0,1,0,sales,low
21,0.38,0.55,2,147,3,0,1,0,sales,low
22,0.09,0.95,6,304,4,0,1,0,sales,low
23,0.46,0.57,2,139,3,0,1,0,sales,low
24,0.40,0.53,2,158,3,0,1,0,sales,low
25,0.89,0.92,5,242,5,0,1,0,sales,low
26,0.82,0.87,4,239,5,0,1,0,sales,low
27,0.40,0.49,2,135,3,0,1,0,sales,low
28,0.41,0.46,2,128,3,0,1,0,accounting,low
29,0.38,0.50,2,132,3,0,1,0,accounting,low
...,...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales,low
171,0.41,0.46,2,160,3,0,1,1,sales,low
172,0.11,0.78,7,278,4,0,1,0,sales,low
173,0.10,0.88,6,284,4,0,1,0,sales,low
174,0.70,0.53,2,274,4,0,1,0,sales,low
175,0.54,0.74,4,164,2,0,1,0,sales,low
176,0.41,0.48,2,148,3,0,1,0,sales,low
177,0.38,0.50,2,140,3,0,1,0,sales,medium
178,0.37,0.51,2,127,3,0,1,0,sales,medium
179,0.11,0.85,6,308,5,0,1,0,sales,medium
180,0.40,0.47,2,146,3,0,1,0,sales,medium
181,0.10,0.84,6,261,4,0,1,0,accounting,medium
182,0.89,0.99,5,257,5,0,1,0,accounting,medium
183,0.11,0.80,6,285,4,0,1,0,accounting,medium
184,0.36,0.55,2,141,3,0,1,0,hr,medium
185,0.40,0.46,2,127,3,0,1,0,hr,medium
186,0.09,0.85,6,297,4,0,1,0,hr,medium
187,0.40,0.46,2,143,3,0,1,0,hr,medium
188,0.37,0.55,2,152,3,0,1,0,technical,medium
189,0.44,0.51,2,156,3,0,1,0,technical,high
190,0.09,0.80,7,283,5,0,1,0,technical,low
191,0.92,0.87,4,226,6,1,1,0,technical,medium
192,0.74,0.91,4,232,5,0,1,0,technical,medium
193,0.09,0.82,6,249,4,0,1,0,technical,medium
194,0.89,0.95,4,275,5,0,1,0,technical,medium
195,0.09,0.80,6,304,4,0,1,0,technical,low
196,0.27,0.54,7,278,3,0,1,0,technical,low
197,0.10,0.91,6,287,4,0,1,0,technical,low
198,0.10,0.89,7,285,4,0,1,0,technical,low
199,0.77,0.94,5,226,6,0,1,0,support,low

Except the output column, all the remaining columns are your inputs. Store all inputs in X.

In [25]:
X = df.iloc[:,0:9]   #input columns
X

,satisfaction_level,last_evaluation,number_of_projects,average_monthly_hours,years_at_company,work_accident,left,promotion_last_5years,department
0,0.38,0.53,2,157,3,0,1,0,sales
1,0.80,0.86,5,262,6,0,1,0,sales
2,0.11,0.88,7,272,4,0,1,0,sales
3,0.72,0.87,5,223,5,0,1,0,sales
4,0.37,0.52,2,159,3,0,1,0,sales
5,0.41,0.50,2,153,3,0,1,0,sales
6,0.10,0.77,6,247,4,0,1,0,sales
7,0.92,0.85,5,259,5,0,1,0,sales
8,0.89,1.00,5,224,5,0,1,0,sales
9,0.42,0.53,2,142,3,0,1,0,sales
10,0.45,0.54,2,135,3,0,1,0,sales
11,0.11,0.81,6,305,4,0,1,0,sales
12,0.84,0.92,4,234,5,0,1,0,sales
13,0.41,0.55,2,148,3,0,1,0,sales
14,0.36,0.56,2,137,3,0,1,0,sales
15,0.38,0.54,2,143,3,0,1,0,sales
16,0.45,0.47,2,160,3,0,1,0,sales
17,0.78,0.99,4,255,6,0,1,0,sales
18,0.45,0.51,2,160,3,1,1,1,sales
19,0.76,0.89,5,262,5,0,1,0,sales
20,0.11,0.83,6,282,4,0,1,0,sales
21,0.38,0.55,2,147,3,0,1,0,sales
22,0.09,0.95,6,304,4,0,1,0,sales
23,0.46,0.57,2,139,3,0,1,0,sales
24,0.40,0.53,2,158,3,0,1,0,sales
25,0.89,0.92,5,242,5,0,1,0,sales
26,0.82,0.87,4,239,5,0,1,0,sales
27,0.40,0.49,2,135,3,0,1,0,sales
28,0.41,0.46,2,128,3,0,1,0,accounting
29,0.38,0.50,2,132,3,0,1,0,accounting
...,...,...,...,...,...,...,...,...,...
170,0.81,0.99,4,259,5,0,1,0,sales
171,0.41,0.46,2,160,3,0,1,1,sales
172,0.11,0.78,7,278,4,0,1,0,sales
173,0.10,0.88,6,284,4,0,1,0,sales
174,0.70,0.53,2,274,4,0,1,0,sales
175,0.54,0.74,4,164,2,0,1,0,sales
176,0.41,0.48,2,148,3,0,1,0,sales
177,0.38,0.50,2,140,3,0,1,0,sales
178,0.37,0.51,2,127,3,0,1,0,sales
179,0.11,0.85,6,308,5,0,1,0,sales
180,0.40,0.47,2,146,3,0,1,0,sales
181,0.10,0.84,6,261,4,0,1,0,accounting
182,0.89,0.99,5,257,5,0,1,0,accounting
183,0.11,0.80,6,285,4,0,1,0,accounting
184,0.36,0.55,2,141,3,0,1,0,hr
185,0.40,0.46,2,127,3,0,1,0,hr
186,0.09,0.85,6,297,4,0,1,0,hr
187,0.40,0.46,2,143,3,0,1,0,hr
188,0.37,0.55,2,152,3,0,1,0,technical
189,0.44,0.51,2,156,3,0,1,0,technical
190,0.09,0.80,7,283,5,0,1,0,technical
191,0.92,0.87,4,226,6,1,1,0,technical
192,0.74,0.91,4,232,5,0,1,0,technical
193,0.09,0.82,6,249,4,0,1,0,technical
194,0.89,0.95,4,275,5,0,1,0,technical
195,0.09,0.80,6,304,4,0,1,0,technical
196,0.27,0.54,7,278,3,0,1,0,technical
197,0.10,0.91,6,287,4,0,1,0,technical
198,0.10,0.89,7,285,4,0,1,0,technical
199,0.77,0.94,5,226,6,0,1,0,support

In [26]:
X.shape

(200, 9)

Select one column from your data(which is your output). Store output in y

In [27]:
y = df.salary
y

0         low
1      medium
2      medium
3         low
4         low
5         low
6         low
7         low
8         low
9         low
10        low
11        low
12        low
13        low
14        low
15        low
16        low
17        low
18        low
19        low
20        low
21        low
22        low
23        low
24        low
25        low
26        low
27        low
28        low
29        low
        ...
170       low
171       low
172       low
173       low
174       low
175       low
176       low
177    medium
178    medium
179    medium
180    medium
181    medium
182    medium
183    medium
184    medium
185    medium
186    medium
187    medium
188    medium
189      high
190       low
191    medium
192    medium
193    medium
194    medium
195       low
196       low
197       low
198       low
199       low
Name: salary, Length: 200, dtype: object

Split the data with a specific random state and make 25% of the data for testing and 75% of the data for training

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(150, 9)
(50, 9)
(150,)
(50,)